name: Test

on:
  push:
  pull_request:
    
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - sys: mingw64
    name: "Setup MSYS-2 64-Bit"
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "Setup MSYS2"
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: >-
          mingw-w64-x86_64-openssl
          git
          curl
    # --------------------
    - name: "Build Tool"
      run: |
        echo "Hello World !"
    # --------------------
    - name: Download artifact
      uses: actions/download-artifact@v4
